### ISSUE TITLE
navigator.oscpu is nonstandard, resulting in no browser info logged

### ISSUE THREAD

**Issue by kirbysayshi** [sebpiq/rhizome#106]
websockets.Client sets `?os=` `navigator.oscpu`, which is blank or undefined in chrome, safari, and firefox. this results in the server never logging the os/browser fields in the connections.db when stats are enabled.

A quick hack to make stats work again:

```
window.navigator.oscpu = window.navigator.oscpu || window.navigator.platform;
```

**Comment by sebpiq** [comment]
thanks for this !

**Comment by kirbysayshi** [comment]
Cool! I found out that my "quick hack" threw an error in some browsers because navigator.oscpu is read-only.

**Comment by sebpiq** [comment]
No worries, I didn't like setting oscpu, so I adapted your hack : https://github.com/sebpiq/rhizome/blob/91b8261898bddcb722083718559a1c0065e30edd/lib/websockets/Client.js#L161
