### ISSUE TITLE
events.db and connections.db are never saved to disk anymore

### ISSUE THREAD

**Issue by kirbysayshi** [sebpiq/rhizome#120]
Is this by design? As far as I can tell, in ConnectionManager there is never a call to save them to disk.

**Comment by sebpiq** [comment]
It is saved there : 
https://github.com/sebpiq/rhizome/blob/master/lib/connections/ConnectionManager.js#L64

Why do you ask, did you get any bug / weird behaviour related to this?

**Comment by kirbysayshi** [comment]
I haven't seen any strange behavior, aside from the files not being on my disk :)

https://github.com/sebpiq/rhizome/blob/master/lib/connections/ConnectionManager.js#L69 calls eventInsert, but that just puts the events into the events collection. Nothing persists that events collection to disk. There isn't a line in the codebase (as far as I can tell) that calls fs.writeFile (or something like it) using the events.db or connections.db filenames.

**Comment by sebpiq** [comment]
eventInsert is implemented by instances of Store, which are implemented here : https://github.com/sebpiq/rhizome/blob/master/lib/connections/persistence.js

There is 2 stores at the moment : one does nothing, the other persists to disk using nedb. If you have configured rhizome to use a persisting store it should work. Can I see your config file?

**Comment by kirbysayshi** [comment]
After a bunch of digging, it turns out it was a permissions issue. 😅 

in the finder / sublime text, connections.db and events.db were missing. `ls -lah` showed them though! since I need to start the server using sudo for port 80, those two files had been created with 644 root:root.

I'm pretty embarrassed by this... i thought perhaps because I'd been using rhizome in cluster / as components I'd missed something. Sorry about this false report!

**Comment by sebpiq** [comment]
Haha! No worries! It's better false alarm, then missing a bug ;)
