### ISSUE TITLE
some questions about getting setup

### ISSUE THREAD

**Issue by tatecarson** [sebpiq/rhizome#124]
Hello, 

Thanks for doing this! It was very easy to get setup and running, perfect for artists starting out. I'm doing a project where I want to send notation to people's phones during a performance from p5js that is being triggered by supercollider over osc. I'm a little confused about what the best way to go about the p5js part. I have it setup so that the example webpage is displaying p5js and running the server but how do I send messages to it from supercollider? 

thanks

**Comment by sebpiq** [comment]
Hello! Glad you got it running at least :)
In the `examples/base` you have a SuperCollider file which sends OSC messages to the server! I haven't updated it for a while, because I don't use SC very often ... but it will probably still work!
Basically you should just send an OSC message to the address IP / port where the rhizome OSC server is running. If you used the example config file, the port should be `9000` and if you run SC and rhizome on the same computer, you can just send to `localhost` instead of using an IP address.
Then, in order to receive messages from your web page, you should subscribe to an OSC address with the rhizome client in JavaScript. So start the client, and when started send a subscribe message, and add a `.on('message', ... )` handler to the rhizome client : 

```
rhizome.start(function(err) {
    rhizome.send('/sys/subscribe', ['/bla/blo']) // Replace by OSC addresses you will send to with SC
    rhizome.send('/sys/subscribe', ['/bli/blu'])
})

rhizome.on('message', function(address, args) { 
    if (address === '/bla/blo') doSomething()
    else if (address === '/bli/blu') doSomethingElse()
})
```

Was that helpful?

**Comment by tatecarson** [comment]
So I don't have to setup the osc port number in the rhizome.js file? I added:   

```
client.on('message', function(address, args) {
    if (address === '/sc') {console.log('getting osc')}
})
```

just to see if it was working. Here's my SC code: 

```
b = NetAddr.new("localhost", 9000);

// Subscribing to receive all messages
b.sendMsg("/sys/subscribe", 9002, "/");

// Now sending stuff
b.sendMsg("/sc", "there");
```

what am I missing? 

Thanks for the quick response.

**Comment by sebpiq** [comment]
no you don't have to modify any file from rhizome, and the browser part of your application doesn't need to know anything about the OSC server. Can you post your Javascript code and your config file? I can have a look and tell you what could be the problem.
You can also activate the log by running `export DEBUG=rhizome*` before starting the server in your terminal. Then the server will be much more verbose and tell you if it receives messages, subscribed clients, etc ...

**Comment by sebpiq** [comment]
also, which OS are you on?

**Comment by tatecarson** [comment]
I'm on OSX. 

rhizome.js: 
```
var client
$(function() {
  client = new rhizome.Client()

  // `rhizome.start` is the first function that should be called.
  // The function inside is executed once the client managed to connect.
  client.start(function(err) {
    if (err) {
      $('body').html('client failed starting : ' + err)
      throw err
    }

    $('#send').submit(function(event) {
      event.preventDefault()
      var address = $('#address').val()
        , args = $('#args').val()
      if (args.length)
        args = args.split(' ').map(function(arg) { return JSON.parse(arg) })
      else args = []
      client.send(address, args)
    })

    // We want to receive all the messages, so we subscribe to '/'
    client.send('/sys/subscribe', ['/'])
  })

  client.on('message', function(address, args) {
    $('#received .message').slice(20).remove()
    var message = $('<div class="message"><span class="ad"></span><span class="ar"></span></div>')
      .prependTo('#received')
    message.find('.ad').html(address)
    message.find('.ar').html(args.map(function(arg) { return JSON.stringify(arg) }).join(' '))
  })

  client.on('connected', function() {
    alert('connected!')
  })

  client.on('connection lost', function() {
    alert('connection lost!')
  })

  client.on('server full', function() {
    alert('server is full!')
  })

  client.on('message', function(address, args) {
    if (address === '/sc') {console.log('getting osc')}
  })

})
```

config file: 
```
var fs = require('fs')
  , path = require('path')

// Create a directory to store data which will be used
// to restore the server in case of crash.
var storeDir = path.join(__dirname, 'tmp') 
if (!fs.existsSync(storeDir)) fs.mkdirSync(storeDir)

module.exports = {

  servers: [
    // Start the HTTP server running on port 8000
    // and serving static files from `./pages` 
    {
      type: 'http',
      config: {
        port: 8000,
        staticDir: path.join(__dirname, 'pages')
      }
    },

    // Start the websockets server running on the same port as the HTTP server
    {
      type: 'websockets',
      config: {
        port: 8000,
        maxSockets: 5000
      }
    },

    // Start the OSC server on port 9000
    {
      type: 'osc',
      config: {
        port: 9000
      }
    }
  ],

  // Configure data to be stored in `./tmp`
  connections: { 
    store: storeDir,
  }
}
```
If all that looks ok then it must be in SC. Do you always run these servers locally and then use wifi or have you ever put them on a cloud server? I'm trying to wrap my head around that, wondering if you ever bother with it. 

thanks again.

**Comment by tatecarson** [comment]
Ah, the debug shows that supercollider is sending osc to the server, so that part is working.

**Comment by sebpiq** [comment]
Yes ... sorry, it's my mistake. I am preparing a new release, so I updated the examples, but I shouldn't have done that in the master. You have rhizome version 0.7 installed right?

Then the Javascript should be : 

```javascript
$(function() {

  // `rhizome.start` is the first function that should be called.
  // The function inside is executed once the client managed to connect.
  rhizome.start(function(err) {
    if (err) {
      $('body').html('client failed starting : ' + err)
      throw err
    }

    $('#send').submit(function(event) {
      event.preventDefault()
      var address = $('#address').val()
        , args = $('#args').val()
      if (args.length)
        args = args.split(' ').map(function(arg) { return JSON.parse(arg) })
      else args = []
      rhizome.send(address, args)
    })

    // We want to receive all the messages, so we subscribe to '/'
    rhizome.send('/sys/subscribe', ['/'])
  })

  rhizome.on('message', function(address, args) {
    $('#received .message').slice(20).remove()
    var message = $('<div class="message"><span class="ad"></span><span class="ar"></span></div>')
      .prependTo('#received')
    message.find('.ad').html(address)
    message.find('.ar').html(args.map(function(arg) { return JSON.stringify(arg) }).join(' '))
  })

  rhizome.on('connected', function() {
    alert('connected!')
  })

  rhizome.on('connection lost', function() {
    alert('connection lost!')
  })

  rhizome.on('server full', function() {
    alert('server is full!')
  })

  rhizome.on('message', function(address, args) {
    if (address === '/sc') {console.log('getting osc')}
  })

})
```

Basically replacing all `client` by `rhizome`. In the previous version (0.7 ... the one you probably use) a client was created automatically for you. The example you should follow is there (older version of the project) : https://github.com/sebpiq/rhizome/tree/1a98ce425cb22e9267ee40c7f7ce7711070ece28

Also, you should open your browser console and see if you get some errors! Normally these errors should have shown up ...

**Comment by tatecarson** [comment]
Ok, I think it wasn't working because I was just looking at the index file instead of the localhost. Seems to all be good now. Very new to server web stuff! 

Once I figure out what I want to do with this i'll probably have some more questions, hope that's ok. 

Would you ever host this page on a server so that you didn't have to rely on wifi and the people could just access it through their phones 3g? Is that more unstable? 

By the way, the SC file example should be .scd, i think the .sc technically works but that's the extension for a class file, so it might confuse some people. If you were interested in expanding the examples for supercollider or needed any help I can try to contribute. I'll share whatever I come up with.

**Comment by sebpiq** [comment]
Glad you figured it out! Sure, don't hesitate to ask more questions if you need.

I hosted it on a server before, and people were able to access it with 3G without any problem. In fact it is easier than setting-up your own wifi.

Thanks! I didn't know difference between .scd and .sc. I will rename it.

Good luck with your project!
