### ISSUE TITLE
rhizome with forever? 

### ISSUE THREAD

**Issue by tatecarson** [sebpiq/rhizome#129]
I'd like to use forever to run rhizome on EC2 so I don't have to use the terminal to start it before  a performance, so there's less things to worry about. Forever runs your script using `forever start app.js` so I can't figure out how to get it to use `rhizome config.js`. `forever rhizome config.js` doesn't work. Have you ever used this? Maybe there's a way I can change the way rhizome is called back to start in order to use forever? 

thanks again.

**Comment by sebpiq** [comment]
hey! Sorry for slow answer. I also use forever, and I usually call the whole path for example `forever node /path/to/rhizome/bin/rhizome.js config.js`

**Comment by tatecarson** [comment]
I can't quite get it to work. 
This starts rhizome fine: 
`node /usr/local/lib/node_modules/rhizome-server/bin/rhizome.js  config.js` 

but this: 
`forever node /usr/local/lib/node_modules/rhizome-server/bin/rhizome.js  config.js` 

throws 
`error:   Cannot start forever
error:   script /home/ubuntu/node does not exist.`

Any idea why? That's obviously the correct path because it starts rhizome, but just doesn't work with forever in front of it. 

thanks again.

**Comment by sebpiq** [comment]
aah sorry my mistake. Here is the exact command in run forever with : `sudo /Users/localadmin/.nvm/versions/node/v0.12.7/bin/forever start ../fields/backend/main.js config.js` adapt it to your system!

**Comment by tatecarson** [comment]
Hmm can you think of any reason why this wouldn't be working: 
`sudo ~/.nvm/versions/node/v4.4.2/bin/forever start /usr/local/lib/node_modules/rhizome-server/bin/rhizome.js config.js`

**Comment by sebpiq** [comment]
Hmm no ... not really. What error message do you get?

**Comment by tatecarson** [comment]
Unfortunately there is no error. Forever says it's started but it just doesn't start rhizome. This is what happens: 
```
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: /usr/local/lib/node_modules/rhizome-server/bin/rhizome.js
```

**Comment by sebpiq** [comment]
then you have some other bug ... activate logging to see it : 

```
...forever -a -l /tmp/rhizome.log start ...
```

and check out what's in the log with : 

```
tail -n 30 /tmp/rhizome.log
```
