### ISSUE TITLE
Trouble w config

### ISSUE THREAD

**Issue by jeremyzuckerman** [sebpiq/rhizome#138]
Hi. I'm trying to run one of the example config files but am getting a 'Cannot find module <path of file>'. Any idea what's causing this?

e.g. rhizome rhizome-config.js

Many thanks!

p.s. forgive me is this isn't the place for this! I'm new to this community.

**Comment by jeremyzuckerman** [comment]
I had to cd to the directory containing the config file. Cheers!

**Comment by sebpiq** [comment]
Ha sorry I was so slow @jeremyzuckerman ! Glad you figured it out!

**Comment by jeremyzuckerman** [comment]
thanks seb!

**Comment by sebpiq** [comment]
;)
