### ISSUE TITLE
Instruction for a setup in a local network or a web page in a server.

### ISSUE THREAD

**Issue by MatiasDelera** [sebpiq/rhizome#139]
I need help. The tutorial on : http://funktion.fm/#post/rhizome-interactive-performances-and-network-topologies is down. I had the system running locally  but I need to make a hosted web page for colaborative access with phones and computers in the audience. Any tip will be appreciated

**Comment by sebpiq** [comment]
Hi @MatiasDelera ! The link is out-dated. This one works : http://funktion.fm/news/network-topologies
I will fix the readme to point to the new link!
