### ISSUE TITLE
drawing-wall example - blob error

### ISSUE THREAD

**Issue by taylorbf** [sebpiq/rhizome#75]
Hi Sebastien,

Love this project and the Parts example is working great for me.

I'm trying out the drawing-wall example, and I've caused some errors.

I can load the page and draw things, but the blobs are not sending.

First, I ran `rhizome config-server.js` and see success. I can load the webpage.

In a different terminal I ran `rhizome config-blobs.js` and see this:

```
Rhizome 0.6.0 running.
(!) no http server
(!) no websockets server
(!) no osc server
```

When I open the Processing sketch it logs this, which looks fine.

```
OscP5 0.9.9 infos, comments, questions at http://www.sojamo.de/oscP5

### [2015/3/18 20:14:7] PROCESS @ OscP5 stopped.
### [2015/3/18 20:14:7] PROCESS @ UdpClient.openSocket udp socket initialized.
### [2015/3/18 20:14:8] PROCESS @ UdpServer.start() new Unicast DatagramSocket created @ port 9001
### [2015/3/18 20:14:8] PROCESS @ UdpServer.run() UdpServer is running @ 9001
### [2015/3/18 20:14:8] INFO @ OscP5 is running. you (192.168.1.4) are listening @ port 9001
subscribed successfully to /drawing
successfully configured the blob client
```

When I try to send blobs, my Terminal logs this:

```
[object Object] blob client refused connection
```

Running this in Chrome on a Mac. Any help is great, thanks!

**Comment by sebpiq** [comment]
Hi Ben!

You used the wrong command to start the blob client! You should run `rhizome-blobs config-blobs.js` and not `rhizome ...` ! With that it should work :) please tell me if it does!

**Comment by taylorbf** [comment]
Splendid, I overlooked that, thanks!
