### ISSUE TITLE
safari ios 6.1.6 now gives "expects binary data"

### ISSUE THREAD

**Issue by redFrik** [sebpiq/rhizome#78]
after updating rhizome to 0.6.0 (from old install 29sept2014) i can no longer connect it to my old ipod touch (running ios 6.1.6).
both my own webapp and rhizome's own base example starts, subscribes and the rhizome.on('connected', function fires on the ipod, but after that the client locks up and no other messages are received. the rhizome server reports...
```
GET / 200 2ms - 1.81kb
GET /rhizome/rhizome.js 200 71ms - 267.06kb
GET /js/jquery-2.1.0.min.js 304 1ms
GET /css/styles.css 304 0ms
expects binary data
```

in comparison i can connect with both osx 10.10.3 and an ipad with ios 8.3. the error message "expects binary data" does not show up for these devices.

**Comment by sebpiq** [comment]
Yes, I've had that too ... I have changed the way the messages are sent, it used to be JSON, now it is OSC-encoded binary data, so that might mean that some older browsers are not supported anymore. I have to look into it, and either reflect this in `WebSocket.Client.isSupported` or try to fix it if possible.

**Comment by sebpiq** [comment]
A simple fix for this would be to have 2 possibilities of sending messages. OSC blob as is done now + something else. Possibly JSON or plain text. When the message doesn't contain a blob, the other version (JSON?) is used by default.

**Comment by sebpiq** [comment]
This commit eab71b70e91cda8eaf8b1d391a5f45e56e921d91 though it doesn't solve the issue at least should filter out devices that don't support rhizome (hopefully).

@redFrik it would be great if you could try with your ipod and see if `rhizome.start(err)` returns an error "this device is not supported"

**Comment by redFrik** [comment]
was just about to test the new commit (thanks) but the problem below occurred.  it might be due to my new laptop and some missing dependency.

in ~/rhizome/examples/base (master)

```
$ rhizome config.js
/usr/local/lib/node_modules/rhizome-server/lib/connections/persistence.js:185
        state.nsTree = state.nsTree.map(function(nodeData) {
                                   ^
TypeError: Cannot read property 'map' of undefined
    at /usr/local/lib/node_modules/rhizome-server/lib/connections/persistence.js:185:36
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by sebpiq** [comment]
Ok thanks for finding this, I added a fix 725ad51d3efc220fc3d5e45de2cdcb63ccb7840b so this doesn't happen anymore.

You might also try to delete the files with old data (by default  )

**Comment by sebpiq** [comment]
Also, I don't know with which version you test, but all these fixes are not yet pushed to npm, so you need to install rhizome from the branch develop of this repository.

I you haven't done so, you can do it by running : 

`npm uninstall -g rhizome-server`

to uninstall the old version, then install the new version with : 

`npm install -g git://github.com/sebpiq/rhizome.git#develop`

**Comment by redFrik** [comment]
still the same... `expects binary data` is printed in the terminal.
on the ipod i do get the example webpage and it alerts 'connected!', but when i inspect the page using laptop+safari i see `WebSocket network error: The operation couldn’t be completed. No such file or directory` in the console.
anything else i can test?

**Comment by sebpiq** [comment]
damn ... I've never seen anything like that. Do you have any stack trace with the debugger?

I've modified a bit the base example, adding slightly more infos to see if we can get something meaningful. Also I prevent the socket to connect if the client doesn't support the required features (which apparently I had forgotten to do before). Could you test with [this example](https://www.dropbox.com/s/takfw5idqkk7pur/examples-base.zip?dl=0) please ? 

Thanks a lot for your help :)

**Comment by redFrik** [comment]
now the websocket network error is gone and i see:
`ws://192.168.1.51:8000/?queueIfFull=true&id=ELeBqvnUcqXZd7Lc&os=&browser=Mozilla%2F5.0%20(iPod%3B%20CPU%20iPhone%20OS%206_1_6%20like%20Mac%20OS%20X)%20AppleWebKit%2F536.26%20(KHTML%2C%20like%20Gecko)%20Version%2F6.0%20Mobile%2F10B500%20Safari%2F8536.25`
else like before (says expects binary data in terminal and connected in ios safari)

**Comment by sebpiq** [comment]
damn ... I really need to get hold of one of these devices. That's the only way I can hope to fix this bug.

**Comment by redFrik** [comment]
it's not such an important bug.  i can live with it.  thanks for all your effort.

**Comment by sebpiq** [comment]
Yes, I can live with it too, but it means that some devices won't work, without any feedback to the user that it is actually not working ... and that's not good. So I'll definitely come back to this.

**Comment by kirbysayshi** [comment]
I believe this is also happening on iOS 7 as well. A friend's iPhone 5S behaves the exact same way connecting to my instance of Rhizome 0.7.0.

**Comment by sebpiq** [comment]
Dammit! Can't find a device that would have the same problem! I have an iphone here, but it's iOS8 and works fine, and several android devices which all work ok ... So basically can't really debug. It's annoying cause I think it's a biggie. If one of you with the bug could look at it, that'd be awesome!

**Comment by kirbysayshi** [comment]
Yes, I discovered that it's extremely hard to downgrade and iOS device now too... so you have to just find one in the wild.

If I have time I'll try to debug with my friend's phone, but I'm not really sure how... haven't dug into websockets too much at a low level.

**Comment by sebpiq** [comment]
The baseline of this bug is that the message arrives on the server side, but the server expects binary messages. Therefore I test whether a message is binary and if not, refuses it and throw an error : 

https://github.com/sebpiq/rhizome/blob/master/lib/websockets/Server.js#L222

basically, I'd need to figure out exactly what is not supported by the WebSocket, and in which condition does the message arrive in the other side. If arrives in a readable state, but the flag `binary` is simply not set, maybe the line I posted above simply need to be fixed to account for this case. So I think if you can get your hand on your friend's phone, just put a `debugger` instruction on that line, and test whether the `flags.binary` is set to `false` (it should be), and then whether even if it is set to false you can anyways read the message ...

**Comment by sebpiq** [comment]
By the way, this should be resolved in master by this 05c721f5b684ed625c3af041049d891b808b7e61 and this 7366cc9ee6e034bc641af7045e78217491faa16d and I am now implementing automated cross-browser tests so that this won't happen again :)

**Comment by redFrik** [comment]
yes, i just confirmed that rhizome 0.7.1 now works with my old ios ipod. thank you.

**Comment by agargara** [comment]
Thank you for fixing this! It works with my iOS 6.1 simulator now that I updated to 0.7.1.

**Comment by sebpiq** [comment]
Glad that it works now :)
