### ISSUE TITLE
Network topology diagram

### ISSUE THREAD

**Issue by sebpiq** [sebpiq/rhizome#92]
Make a wiki about wifis, and publish a topology diagram of our wifi setup.

**Comment by sebpiq** [comment]
Maybe a blog post instead?

**Comment by kirbysayshi** [comment]
+1 this would be extremely useful! I'm investigating this myself and any knowledge gained through your experiments you can share would be so helpful!

**Comment by sebpiq** [comment]
Done : http://funktion.fm/#post/rhizome-interactive-performances-and-network-topologies
